/**
 * @fileoverview
 * The monolithic Angular app which manages all grid chrome, views,
 * and server interactions.
 */
// TODO: Use @export for scope variables rather than string property access.
goog.provide('windmill.module');

goog.require('windmill.Grid');
// goog.require('windmill.GridRenderer');
goog.require('windmill.GridUi');
goog.require('windmill.GridUiHook');
// goog.require('goog.array');
// goog.require('goog.asserts');
// goog.require('goog.dom.classlist');
// goog.require('goog.object');



// angular.element(document).ready(function() {
// document.addEventListener( "DOMContentLoaded", function() {
window.addEventListener( "load", function() {
  var index = 0;
  var PUZZLES = [
    'CAUSAggDEgIoAxICCAQ=_0', // Initial start
    'CAUSAigEEgIIBBICKAISAggBEgASAggBEgASAggBEgASAggBEgIoAxICCAESABICCAESABICCAESABICCAESAigDEgIIARIAEgIIARICCAMSAggBEgASAggBEgA=_0', // Up-and-right
    'CAkSABICCAESABICCAESAigEEgIIBBICCAESAigFEgIIARIAEgIIARICKAUSAggBEgASAggBEgIoBRICCAESABICCAESABICCAESAigDEgIIARICKAUSAggBEgIoAxICCAESAigPEgIIARIAEgIIARICKAMSAggBEgIIAxICCAESAigFEgIIARIA_0', // 4x4 simple maze
    'CBUSAigLEgIIARICKAUSAggBEgIoAhICCAQSAggBEgIoAxICCAESABICCAESAigDEgIIARICKAMSAggBEgASAggBEgIoBRICCAESABICCAESAigDEgIIARIAEgIIARICKAkSAggBEgIoBxICCAESAigFEgIIARIAEgIIARIAEgIIARICKAMSAggBEgIoAxICCAESABICCAESAigDEgIIARIAEgIIARICKAMSAggBEgIoAxICCAESAggBEgIoAhICCAESAigDEgIIARIAEgIIARICKAUSAggBEgIoAxICCAESAigFEgIIARICKAcSAggBEgIoAxICCAESAigEEgIIARICKAQSAggBEgASAggBEgASAggBEgASAggBEgASAggBEgIoAxICCAESAigDEgIIARIAEgIIARIAEgIIARICKAcSAggBEgIoAxICCAESAigDEgIIARIAEgIIARICKAUSAggBEgASAggBEgIoCRICCAESAigFEgIIARIAEgIIARICKAMSAggBEgIoBRICCAESABICCAESAigJEgIIARICKAUSAggBEgASAggBEgIoCRICCAESAigFEgIIARICKAcSAggBEgASAggBEgIoAxICCAESABICCAESAigHEgIIARIAEgIIARIAEgIIARICKAMSAggBEgASAggBEgIoAxICCAESABICCAESABICCAESAigFEgIIARICKA8SAggBEgASAggBEgIoCRICCAESABICCAESAigDEgIIARIAEgIIARIAEgIIARICKAUSAggBEgIoBxICCAESABICCAESAigHEgIIARICKAMSAggBEgASAggBEgIoAxICCAESAigDEgIIARIAEgIIARICKAUSAggBEgIIARICKAISAggBEgIoAxICCAESABICCAESAigFEgIIARIAEgIIARICKAgSAggDEgIoBhICCAESAigHEgIIARICKAU=_0', // 10x10 large maze

    // TODO: Large maze with multiple starts

    // bw teaching section

    'CAMSAigEEgQIBxABEgASAggDEgASAggEEgASBAgHEAISAigE_0', // bw intro 1x2
    'CAMSAigCEgIIBBIAEgQIBxABEgIoBRIECAcQAhIAEgIIAxICKAI=_0', // bw intro 1x2
    'CAMSAigCEgIIBBIAEgQIBxABEgIoBRIECAcQARICKAUSBAgHEAISABICCAMSAigC_0', // bw intro 1x3
    // 'CAMSAigCEgIIBBIAEgQIBxABEgIoBRIECAcQAhICKAUSBAgHEAESABICCAMSAigC_0', // bw intro 1x3 (middle)
    'CAUSAigEEgIIBBIAEgQIBxABEgASBAgHEAESAigHEgQIBxABEgASBAgHEAISABICCAMSAigE_0', // bw intro 2x2
    'CAcSAigGEgIIBBIAEgQIBxABEgASBAgHEAESABIECAcQARICKAkSBAgHEAESABIECAcQAhIAEgQIBxABEgIoCRIECAcQAhIAEgQIBxACEgASBAgHEAISABICCAMSAigG_0', // bw intro 3x3
    'CAcSAigIEgQIBxABEgASBAgHEAESABIECAcQARICKAkSBAgHEAESABIECAcQAhIAEgQIBxABEgASAggEEgIoBxIECAcQAhIAEgQIBxACEgASBAgHEAISABICCAMSAigG_0', // bw intro 3x3
    'CAkSAigCEgIIBBICKAcSBAgHEAESAigDEgQIBxACEgASBAgHEAESAigLEgQIBxABEgASBAgHEAESABIECAcQARIAEgQIBxABEgIoCxIECAcQARIAEgQIBxACEgASBAgHEAESABIECAcQARICKAsSBAgHEAISABIECAcQAhIAEgQIBxACEgASBAgHEAESABICCAMSAigI_0', // bw intro 4x4
    'CAkSAigKEgQIBxABEgASBAgHEAESABIECAcQAhIAEgQIBxABEgIoDRIECAcQARIAEgQIBxABEgASBAgHEAESAigJEgIIBBIAEgQIBxABEgASBAgHEAISABIECAcQARIAEgQIBxABEgIoCxIECAcQAhIAEgQIBxACEgASBAgHEAISABIECAcQARIAEgIIAxICKAg=_0', // bw intro 4x4
    'CAkSAigIEgIIBBICKAMSBAgHEAESABIECAcQAhIAEgQIBxABEgIoCxIECAcQARICKAUSBAgHEAESAigLEgQIBxABEgASBAgHEAISABIECAcQARICKA0SBAgHEAISABIECAcQAhIAEgQIBxACEgASBAgHEAESABICCAMSAigI_0', // bw 4x4

    // dot teaching section
    'CAMSAigCEgIIBBICKAQSAggGEgIoBBICCAMSAigC_0', // dot 1x2
    'CAUSAigEEgIIBBICKAISAggGEgASAggGEgIoChICCAMSAigE_0', // dot 2x2

    'CAcSABICCAESAigEEgIIBBICCAESABICCAYSAigJEgIIARICKBESAggGEgASAggBEgASAggGEgIIAxICKAY=_0', // dot 3x3
    'CAcSABICCAESAigEEgIIBBICCAESABICCAYSAigDEgIIBhICKAUSAggBEgIoERICCAYSABICCAESABICCAYSAggDEgIoBg==_0', // dot 3x3
    'CAcSABICCAESAigFEgIIARIAEgIIBhICKAMSAggGEgIIBBIAEgIIAxICKAISAggBEgIoBRICCAYSAigGEgIIAxICKAQSAggGEgASAggBEgASAggGEgIoBw==_0', // dot 3x3
    'CAcSABICCAESAigCEgIIAxIAEgIIAxICCAESABICCAYSAigDEgIIBhICCAQSAigEEgIIARICKAUSAggGEgIoCBICCAMSAigCEgIIBhIAEgIIARIAEgIIBhICKAc=_0', // dot 3x3

    // tetris teaching section
    'CAMSAigCEgIIBBICKAcSCQgJIgUIARIBARIAEgIIAxICKAI=_0', // tetris 1x2
    'CAMSAigCEgIIBBICKA0SCQgJIgUIARIBARIAEgIIAxICKAI=_0', // tetris 1x3
    'CAMSAigCEgIIBBICKA0SCggJIgYIARICAQESABICCAMSAigC_0', // tetris 1x3
    'CAUSAigEEgIIBBICKAsSDAgJIggIAhIEAQABARICKAMSAggDEgIoBA==_0', // tetris 2x2

    'CAcSAigGEgIIBBICKBESDAgJIggIAhIEAQEBARICKBESAggDEgIoBg==_0', // tetris 3x3
    'CAcSAigDEgIIBRICKAISAggEEgIoBhICCAUSAigKEgwICSIICAISBAEBAQESAigREgIIAxICKAQSAggFEgA=_0', // tetris 3x3
    'CAsSAigKEgIIBBICKAoSAggFEgIoCxICCAUSAigaEg4ICSIKCAISBgEBAQABABICKBYSAggFEgIoGhICCAMSAigIEgIIBRIA_0', // tetris 5x5
    'CAsSAigKEgIIBBICKAoSAggFEgIoCxICCAUSAigaEg4ICSIKCAISBgEBAQABABICKBISAggFEgIoAxICCAUSAigaEgIIAxICKAgSAggFEgA=_0', // tetris 5x5


    // 2 piece tetris tutorial
    'CAMSAigCEgIIBBIAEgkICSIFCAESAQESAigFEgkICSIFCAESAQESABICCAMSAigC_0', // 1x2
    'CAMSAigCEgIIBBIAEgkICSIFCAESAQESAigLEgkICSIFCAESAQESABICCAMSAigC_0', // 1x3
    'CAcSAigGEgIIBBICKAMSCggJIgYIAhICAQESAigZEgoICSIGCAISAgEBEgIoBRICCAMSAigG_0', // 3x3
    'CAcSAigGEgIIBBICKBMSCggJIgYIAhICAQESAigJEgoICSIGCAISAgEBEgIoBRICCAMSAigG_0', // 3x3
    'CAkSAigIEgIIBBICKCcSCwgJIgcIAxIDAQEBEgIoAxILCAkiBwgBEgMBAQESAigTEgIIAxICKAg=_0', // 4x4
    'CAkSAigIEgIIBBICKBgSAggFEgIoDhILCAkiBwgDEgMBAQESAigDEgsICSIHCAESAwEBARICKBMSAggDEgIoCA==_0', // 4x4

    // multi-piece not-exactly-tutorial
    'CAsSAigKEgIIBBICKBASAggFEgIoCBIKCAkiBggCEgIBARICKAISAggFEgIoEhIMCAkiCAgCEgQBAAEBEgIoGRIMCAkiCAgCEgQBAQEBEgIoGRICCAMSAigK_0', // 4x4 (3 pieces all moved)
    'CAsSAigKEgIIBBICKBkSCggJIgYIAhICAQESAigTEgwICSIICAISBAEAAQESAigbEgwICSIICAISBAEBAQESAigZEgIIAxICKAo=_0', // 5x5 all pieces moved (maybe duplicate)

    // Star tutorial
    'CAMSAigEEgQICBAIEgASAggDEgASAggEEgASBAgIEAgSAigE_0', // 1x2
    'CAUSAigEEgIIBBIAEgQICBAIEgASBAgIEAgSAigHEgQICBAIEgASBAgIEAgSABICCAMSAigE_0', // 2x2
    'CAcSAigGEgIIBBICKA8SBAgIEAgSABIECAgQCBIAEgQICBAIEgIoCxIECAgQCBICKAMSAggDEgIoBg==_0', // 3x3
    'CAcSAigGEgIIBBIAEgQICBAFEgASBAgIEAgSABIECAgQCBICKAkSBAgIEAUSAigDEgQICBAFEgIoCRIECAgQCBIAEgQICBAIEgASBAgIEAUSABICCAMSAigG_0', // 3x3 2-colors
    'CAkSAigIEgIIBBIAEgQICBACEgASBAgIEAISABIECAgQAhIAEgQICBACEgIoCxIECAgQARIAEgQICBABEgASBAgIEAYSABIECAgQBhICKAsSBAgIEAUSABIECAgQCBIAEgQICBAIEgASBAgIEAYSAigLEgQICBAFEgASBAgIEAgSABIECAgQCBIAEgQICBAGEgASAggDEgIoCA==_0', // 4x4 4-colors


    // star and square example
    'CAUSAigEEgIIBBIAEgQIBxABEgIoCxIECAgQAhICKAcSBAgHEAISAigDEgIIAxICKAQ=_0', // 1x3



  'CAkSAigEEggIBBoECAAQARICKAUSBAgIEAUSABIECAgQCBIAEgQICBAIEgASBAgIEAISAigLEgQICBAFEgIIBhIECAgQCBIAEgQICBAIEgIIBhIECAgQAhICKAsSBAgIEAUSABIECAgQAxIAEgQICBADEgASBAgIEAISAigLEgQICBAFEgASBAgIEAMSABIECAgQAxIAEgQICBACEgIoBRICCAMSAigE_0', // surfing
  'CAcSAigGEggIBBoECAIQABICKAISAggGEgIoBhICCAYSAigDEgIIBhICKAMSAggKEgIoAhICCAYSAigCEgIIBhIAEgIIBhICCAUSAigDEgIIBhIAEgIIBhICKAISAggDEgIoBg_0', // short walk
  'CA0SAigMEggIBBoECAIQABIAEgwICSIICAISBAEBAQASAigFEgwICSIICAISBAEBAQASAigDEgIIChICKBMSDAgJIggIAhIEAAEBARICKAUSDAgJIggIAhIEAAEBARIAEgIIAxICKAw_0', //gallery

];

  function doStuff(data) {
    var gui;
    var grid = new windmill.Grid();
    grid.initialize(undefined, undefined, data);
    var uiHook = new windmill.GridUiHook();
    uiHook.showToast = function() { alert('toast'); console.log(arguments); };
    uiHook.onSuccess = function(path) {
      // alert('success'); console.log(arguments);
      gui.disappearSnake(200, [], 0);
      gui.dispose();
      index++;
      if (PUZZLES[index]) {
        doStuff(PUZZLES[index]);
      } else {
        alert('All done (for now)');
      }
    };
    gui = new windmill.GridUi(grid, uiHook);
    gui.render();
  }

  doStuff(PUZZLES[index]);

});
